release:
	rebar3 release

main:
	NODE_NAME=web_crawler@localhost RELX_REPLACE_OS_VARS=true _build/default/rel/web_crawler/bin/web_crawler console

b1:
	NODE_NAME=web_crawler_b1@localhost RELX_REPLACE_OS_VARS=true _build/default/rel/web_crawler/bin/web_crawler console

b2:
	NODE_NAME=web_crawler_b2@localhost RELX_REPLACE_OS_VARS=true _build/default/rel/web_crawler/bin/web_crawler console

b3:
	NODE_NAME=web_crawler_b3@localhost RELX_REPLACE_OS_VARS=true _build/default/rel/web_crawler/bin/web_crawler console



